### ISSUE TITLE
请问能否适配X-Wrt？

### ISSUE THREAD

**Issue by microka** [larsonzh/owmwpprt#5]
作者您好，我现在用的是[X-Wrt](https://downloads.x-wrt.com/rom/) ，固件自带的是mwan3plus（看显示mwan3没有安装），但也同时装了luci-app-mwan3提供UI界面
![2023-11-16_033150](https://github.com/larsonzh/owmwpprt/assets/490351/7837473d-44f9-46fb-857b-1c98c2de4d32)
![2023-11-16_033123](https://github.com/larsonzh/owmwpprt/assets/490351/bb919e12-5d85-43d2-adee-bbf7dbd76712)

尝试配置运行lzrules.sh，提示 Package mwan3 is not installed or corrupt. This script cannot be run.
![2023-11-16_033510](https://github.com/larsonzh/owmwpprt/assets/490351/e2eb85d6-e7d7-470a-85f4-8ba7df27c89a)

不敢直接安装mwan3，怕会和mwan3plus冲突，想请问作者X-Wrt能否用上本项目脚本工具？谢谢~

**Comment by larsonzh** [comment]
> 作者您好，我现在用的是[X-Wrt](https://downloads.x-wrt.com/rom/) ，固件自带的是mwan3plus（看显示mwan3没有安装），但也同时装了luci-app-mwan3提供UI界面
> 
> ![2023-11-16_033150](https://github.com/larsonzh/owmwpprt/assets/490351/7837473d-44f9-46fb-857b-1c98c2de4d32)
> 
> ![2023-11-16_033123](https://github.com/larsonzh/owmwpprt/assets/490351/bb919e12-5d85-43d2-adee-bbf7dbd76712)
> 
> 
> 
> 
> 
> 尝试配置运行lzrules.sh，提示 Package mwan3 is not installed or corrupt. This script cannot be run.
> 
> ![2023-11-16_033510](https://github.com/larsonzh/owmwpprt/assets/490351/e2eb85d6-e7d7-470a-85f4-8ba7df27c89a)
> 
> 
> 
> 不敢直接安装mwan3，怕会和mwan3plus冲突，想请问作者X-Wrt能否用上本项目脚本工具？谢谢~

未用过X-Wrt，不太了解。基于op核心的版本太多了，实在顾不过来，目前还没有进一步的适配计划。若喜欢折腾，你可以安装mwan3试试。

**Comment by microka** [comment]
> > 作者您好，我现在用的是[X-Wrt](https://downloads.x-wrt.com/rom/) ，固件自带的是mwan3plus（看显示mwan3没有安装），但也同时装了luci-app-mwan3提供UI界面
> > ![2023-11-16_033150](https://user-images.githubusercontent.com/490351/283227946-7837473d-44f9-46fb-857b-1c98c2de4d32.png)
> > ![2023-11-16_033123](https://user-images.githubusercontent.com/490351/283227967-bb919e12-5d85-43d2-adee-bbf7dbd76712.png)
> > 尝试配置运行lzrules.sh，提示 Package mwan3 is not installed or corrupt. This script cannot be run.
> > ![2023-11-16_033510](https://user-images.githubusercontent.com/490351/283228149-e2eb85d6-e7d7-470a-85f4-8ba7df27c89a.png)
> > 不敢直接安装mwan3，怕会和mwan3plus冲突，想请问作者X-Wrt能否用上本项目脚本工具？谢谢~
> 
> 未用过X-Wrt，不太了解。基于op核心的版本太多了，实在顾不过来，目前还没有进一步的适配计划。若喜欢折腾，你可以安装mwan3试试。

好的，谢谢。
